[tool.poetry]
name = "fullstack-web-development-hw2"
version = "0.1.0"
description = ""
authors = ["Oleh Usatyi <olegysik1@ukr.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
